-dontwarn org.bouncycastle.jsse.BCSSLParameters
-dontwarn org.bouncycastle.jsse.BCSSLSocket
-dontwarn org.bouncycastle.jsse.provider.BouncyCastleJsseProvider
-dontwarn org.conscrypt.Conscrypt$Version
-dontwarn org.conscrypt.Conscrypt
-dontwarn org.conscrypt.ConscryptHostnameVerifier
-dontwarn org.openjsse.javax.net.ssl.SSLParameters
-dontwarn org.openjsse.javax.net.ssl.SSLSocket
-dontwarn org.openjsse.net.ssl.OpenJSSE
-dontwarn org.slf4j.impl.StaticLoggerBinder

# With R8 full mode generic signatures are stripped for classes that are not
# kept. Suspend functions are wrapped in continuations where the type argument
# is used.
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation

# Keep `Companion` object fields of serializable classes.
# This avoids serializer lookup through `getDeclaredClasses` as done for named companion objects.
-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1> {
   static <1>$Companion Companion;
}

# Keep `serializer()` on companion objects (both default and named) of serializable classes.
-if @kotlinx.serialization.Serializable class ** {
   static **$* *;
}
-keepclassmembers class <2>$<3> {
   kotlinx.serialization.KSerializer serializer(...);
}

# Keep `INSTANCE.serializer()` of serializable objects.
-if @kotlinx.serialization.Serializable class ** {
   public static ** INSTANCE;
}
-keepclassmembers class <1> {
   public static <1> INSTANCE;
   kotlinx.serialization.KSerializer serializer(...);
}

# @Serializable and @Polymorphic are used at runtime for polymorphic serialization.
-keepattributes RuntimeVisibleAnnotations,AnnotationDefault

# Keep line numbers (renamed to a single fake file name, since the real per-class file names
# aren't useful once obfuscated) so Crashlytics-deobfuscated stack traces point at a real line,
# not just a class/method. Without this R8 strips line info entirely; it wasn't kept before.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# core:datastore's UserPreferences (and its DarkThemeConfigProto enum) are generated by Wire from
# user_preferences.proto and round-tripped through raw protobuf encode/decode in
# PreferenceSerializer - not reflection, but obfuscating or reordering their fields/members can
# still desync the wire format from what was already written to disk on a user's device, which
# would silently fail to decode existing saved preferences after an update. Same fix as
# MetanMobile's core:datastore for the identical Wire+DataStore setup.
-keep class com.ngapp.quottie.core.datastore.UserPreferences { *; }
-keep class com.ngapp.quottie.core.datastore.* { *; }
-keepclassmembers class com.ngapp.quottie.core.datastore.UserPreferences { public *; }